#!/usr/bin/env bash

# Start MySQL server
service mysql start

# Set up autograder files
cp /autograder/submission/queries.py /autograder/source/queries.py

cd /autograder/source

python3 run_tests.py
